version: '3'

services:
  web:
    build: .
    command: bash -c "python src/user_profile_project/manage.py makemigrations && python src/user_profile_project/manage.py migrate && python src/user_profile_project/manage.py runserver 0.0.0.0:5000"
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust" 
      POSTGRES_DB: userprofile
      POSTGRES_USER: qainfotech
      POSTGRES_PASSWORD: qainfotech
