version: '3'

services:
  web:
    build: .
    command: bash -c "python src/apistatus/manage.py makemigrations && python src/apistatus/manage.py migrate && python src/apistatus/manage.py runserver 0.0.0.0:5000"
    volumes:
      - ./:/code
    ports:
      - "5000:5000"
